#!/bin/sh
# Copyright (c) 2026 Mattia Cabrini
# SPDX-License-Identifier: MIT
#
# install.sh -- interactive installer for net-expandable-logger (FreeBSD),
# invoked by `make install`. It:
#   1. asks the few choices that matter and writes /usr/local/etc/nel.conf;
#   2. installs the framework and collectors under /usr/local/libexec/nel;
#   3. creates the spool directories;
#   4. adds a marked daily entry to /etc/crontab.
# Re-running is safe: it updates everything in place. Must run as root.

set -u

PREFIX=${1:-/usr/local}
SRC=${2:-.}                              # repo root (holds bin/ lib/ collectors/)

LIBEXEC="$PREFIX/libexec/nel"
ETC="$PREFIX/etc"
CONF="$ETC/nel.conf"
CRONTAB="/etc/crontab"
MARK="# net-expandable-logger"           # tags our crontab line so we can find it

[ "$(id -u)" = "0" ] || { echo "install.sh: must be run as root" >&2; exit 1; }

# ask PROMPT DEFAULT -- prompt on the terminal, echo the reply, or DEFAULT if
# the reply is empty. Reads from /dev/tty so it works even when stdin is a pipe.
ask() {
	prompt=$1
	default=$2
	printf '%s [%s]: ' "$prompt" "$default" > /dev/tty
	IFS= read -r answer < /dev/tty
	if [ -n "$answer" ]; then
		printf '%s\n' "$answer"
	else
		printf '%s\n' "$default"
	fi
}

# detect_fw -- guess which firewall is active, for use as a default.
detect_fw() {
	if pfctl -s info >/dev/null 2>&1; then
		echo pf
	elif ipfw list >/dev/null 2>&1; then
		echo ipfw
	else
		echo none
	fi
}

echo "=== net-expandable-logger installer ==="

# --- decide whether to (re)write the configuration --------------------------
if [ -r "$CONF" ]; then
	printf 'A configuration already exists at %s. Reconfigure? [y/N]: ' "$CONF" > /dev/tty
	IFS= read -r reply < /dev/tty
	case "$reply" in
	y|Y) DO_CONF=1 ;;
	*)   DO_CONF=0 ;;
	esac
else
	DO_CONF=1
fi

# --- gather answers and write nel.conf --------------------------------------
if [ "$DO_CONF" = 1 ]; then
	def_host=$(hostname -s 2>/dev/null || hostname)
	def_fw=$(detect_fw)

	HOSTLABEL=$(ask "Host label"                 "$def_host")
	RECIPIENT=$(ask "Recipient e-mail (To:)"     "log@example.org")
	DEPOSIT=$(ask   "Deposit directory (.noeml)" "/var/spool/nel/deposit")
	WORK=$(ask      "Work directory (fragments)" "/var/spool/nel/work")
	MESSAGES_FILE=$(ask "System log file"        "/var/log/messages")
	AUTH_FILE=$(ask "SSH auth log file"          "/var/log/auth.log")
	FIREWALL=$(ask  "Firewall (pf|ipfw|none)"    "$def_fw")
	SIGN_KEY=$(ask  "PGP signing key id (empty = none)" "")

	# A passphrase file only makes sense when a signing key was given.
	SIGN_PASSFILE=""
	[ -n "$SIGN_KEY" ] && SIGN_PASSFILE=$(ask "PGP passphrase file (empty = none)" "")

	CRON_HOUR=$(ask "Cron hour (0-23)"   "21")
	CRON_MIN=$(ask  "Cron minute (0-59)" "0")

	# Regex used by the fallback path of the firewall collectors: which syslog
	# lines to treat as firewall lines.
	case "$FIREWALL" in
	ipfw) FW_SYSLOG_RE="ipfw" ;;
	pf)   FW_SYSLOG_RE="pf: " ;;
	*)    FW_SYSLOG_RE="ipfw|pf: " ;;
	esac

	mkdir -p "$ETC"
	umask 022
	cat > "$CONF" <<CONFEOF
# Copyright (c) 2026 Mattia Cabrini
# SPDX-License-Identifier: MIT
#
# nel.conf -- generated by the installer on $(date '+%Y-%m-%d %H:%M:%S').

HOSTLABEL="$HOSTLABEL"
RECIPIENT="$RECIPIENT"
SUBJECT="\$HOSTLABEL [INFO] - STATUS"

BASE="$LIBEXEC"
LIBDIR="$LIBEXEC"
SVCDIR="$LIBEXEC/collectors"
NEL_LIB="$LIBEXEC/lib.sh"

WORK="$WORK"
DEPOSIT="$DEPOSIT"
GZIP_THRESHOLD=10240

SIGN_KEY="$SIGN_KEY"
SIGN_PASSFILE="$SIGN_PASSFILE"

MESSAGES_FILE="$MESSAGES_FILE"
AUTH_FILE="$AUTH_FILE"

FIREWALL="$FIREWALL"
PFLOG_FILE="/var/log/pflog"
IPFW_LOG_FILE="/var/log/security"
FW_SYSLOG_RE="$FW_SYSLOG_RE"
CONFEOF
	echo "Wrote $CONF"
else
	# Keep the existing config; only ask for the cron time (used further down).
	. "$CONF"
	CRON_HOUR=$(ask "Cron hour (0-23)"   "21")
	CRON_MIN=$(ask  "Cron minute (0-59)" "0")
fi

# --- install framework and collectors ---------------------------------------
mkdir -p "$LIBEXEC/collectors"
install -m 0644 "$SRC/lib/lib.sh"        "$LIBEXEC/lib.sh"
install -m 0755 "$SRC/bin/nel-run"       "$LIBEXEC/nel-run"
install -m 0755 "$SRC/bin/nel-compress"  "$LIBEXEC/nel-compress"
install -m 0755 "$SRC/bin/nel-assemble"  "$LIBEXEC/nel-assemble"
for c in "$SRC"/collectors/*; do
	install -m 0755 "$c" "$LIBEXEC/collectors/$(basename "$c")"
done
echo "Installed framework into $LIBEXEC"

# --- create the spool -------------------------------------------------------
. "$CONF"
mkdir -p "$WORK" "$DEPOSIT"
echo "Spool ready: $WORK , $DEPOSIT"

# --- install the cron entry (idempotent) ------------------------------------
# Rewrite crontab without our old marked line, then append the fresh one.
tmpc=$(mktemp)
grep -v "$MARK" "$CRONTAB" > "$tmpc" 2>/dev/null || true
printf '%s %s * * * root %s %s\n' \
	"$CRON_MIN" "$CRON_HOUR" "$LIBEXEC/nel-run" "$MARK" >> "$tmpc"
install -m 0644 "$tmpc" "$CRONTAB"
rm -f "$tmpc"
echo "Cron entry installed in $CRONTAB at $CRON_HOUR:$CRON_MIN daily"

echo "=== done ==="
